<a href="https://colab.research.google.com/github/MUSSAFARA-RIAZ/Numpy-Learning/blob/main/Numpy_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [91]:
#Numpy- Numerical Python
## In our datasets, we have multiple numerical values to deal with the numerical values -- used to process the numerical values
#Advantages
# Allow several Mathematical operations
# Faster operations


In [92]:
import numpy as np
#List vs Numpy
from time import process_time
#Time taken by a list
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)


0.0009534630000018751


In [93]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.00013186199999637438


In [94]:
#Numpy

In [95]:
type(np_array)

numpy.ndarray

In [96]:
array1=np.array([[1,2,3,4],[5,6,7,8]])
array1.shape

(2, 4)

In [97]:
array2=np.array([1,2,3,4])
array2.shape

(4,)

In [98]:
#Numpy array with multiple dimension
array3=np.array([(1,2,3,4),(5,6,7,8)])
array3.shape

(2, 4)

In [99]:
array4=np.array([(1,2,3,4),(5,6,7,8)],dtype="float")
print(array4)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [100]:
# Initial placeholders in numpy arrays
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [101]:
y=np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [102]:
#array of a particular value
z=np.full((4,5),2,dtype="float")
print(z)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [103]:
# create an identity matrix
indentity_matrix=np.eye(4)
print(indentity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [104]:
#create an numpy array with random values
b=np.random.random((3,4))
print(b)
# all the values are between 0-1

[[0.25394743 0.40072021 0.56113824 0.08815658]
 [0.69760247 0.0794517  0.48565862 0.13382156]
 [0.88527075 0.23152535 0.80727297 0.57258588]]


In [105]:
# random integer value array within the specified range
x=np.random.randint(10,100,(3,5))
print(x)
# 10-100 value

[[22 95 24 54 22]
 [20 15 84 75 63]
 [96 52 94 45 16]]


In [106]:
# array of evenly spaced value
y=np.linspace(10,30,5)
print(y)
# third value is the number of value you want

[10. 15. 20. 25. 30.]


In [107]:
z=np.arange(10,100,5)
# arange method is used to generate evenly spaced values between range and third para is the step value
print(z)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [108]:
# convert a list into numpy array
list1=[1,2,3,4]
np_array=np.asarray(list1)
print(np_array)
np.dtype

[1 2 3 4]


numpy.dtype

In [109]:
# Analysing numpy array

In [110]:
matrix1=np.random.randint(10,100,(6,6))
print(matrix1)

[[97 40 26 73 49 99]
 [22 51 33 71 26 13]
 [77 75 68 83 78 98]
 [94 97 98 45 39 98]
 [84 43 37 76 63 72]
 [45 77 71 10 75 52]]


In [111]:
# dimension
print(matrix1.shape)

(6, 6)


In [112]:
#num of dimension
print(matrix1.ndim)

2


In [113]:
#num of elements in an array
print(matrix1.size)

36


In [114]:
# checking the data types of the values in an array
print(matrix1.dtype)

int64


In [115]:
# Mathematical Operation that can be performed on np array

In [116]:
array1=np.random.randint(10,100,(3,3))
array2=np.random.randint(50,100,(3,3))
print(array1+array2)

[[ 81 103 102]
 [137 181 106]
 [139 134  89]]


In [117]:
print(np.add(array1,array2))
print(np.subtract(array1,array2))
print(np.multiply(array1,array2))
print(np.divide(array1,array2))

[[ 81 103 102]
 [137 181 106]
 [139 134  89]]
[[-61 -81 -26]
 [ 19  17 -86]
 [ -3 -30 -67]]
[[ 710 1012 2432]
 [4602 8118  960]
 [4828 4264  858]]
[[0.14084507 0.11956522 0.59375   ]
 [1.3220339  1.20731707 0.10416667]
 [0.95774648 0.63414634 0.14102564]]


In [118]:
#Array Manipulation
x=np.random.randint(10,100,(2,3))
print(np.transpose(x))

[[49 24]
 [61 88]
 [14 11]]


In [119]:
#Another way to find transpose
print(x.T)

[[49 24]
 [61 88]
 [14 11]]


In [120]:
#Reshaping an array
r1=np.random.randint(10,100,(3,2))
r2=r1.reshape(2,3)
print(r2)

[[23 34 58]
 [96 67 78]]


In [121]:
# The tool flatten creates a copy of the input array flattened to one dimension.
my_array = np.array([[1,2,3],
                        [4,5,6]])
print(my_array.flatten())

[1 2 3 4 5 6]
